#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "laser_controller_types.h"

typedef enum {
    LASER_CONTROLLER_FAULT_CLASS_NONE = 0,
    LASER_CONTROLLER_FAULT_CLASS_INTERLOCK_AUTO_CLEAR,
    LASER_CONTROLLER_FAULT_CLASS_SAFETY_LATCHED,
    LASER_CONTROLLER_FAULT_CLASS_SYSTEM_MAJOR,
} laser_controller_fault_class_t;

typedef enum {
    LASER_CONTROLLER_FAULT_NONE = 0,
    LASER_CONTROLLER_FAULT_INVALID_CONFIG,
    LASER_CONTROLLER_FAULT_NVS_CRC,
    LASER_CONTROLLER_FAULT_WATCHDOG_RESET,
    LASER_CONTROLLER_FAULT_BROWNOUT_RESET,
    LASER_CONTROLLER_FAULT_PD_LOST,
    LASER_CONTROLLER_FAULT_PD_INSUFFICIENT,
    LASER_CONTROLLER_FAULT_LD_RAIL_BAD,
    LASER_CONTROLLER_FAULT_TEC_RAIL_BAD,
    LASER_CONTROLLER_FAULT_IMU_STALE,
    LASER_CONTROLLER_FAULT_IMU_INVALID,
    LASER_CONTROLLER_FAULT_HORIZON_CROSSED,
    LASER_CONTROLLER_FAULT_TOF_STALE,
    LASER_CONTROLLER_FAULT_TOF_INVALID,
    LASER_CONTROLLER_FAULT_TOF_OUT_OF_RANGE,
    LASER_CONTROLLER_FAULT_LD_OVERTEMP,
    LASER_CONTROLLER_FAULT_LAMBDA_DRIFT,
    LASER_CONTROLLER_FAULT_TEC_TEMP_ADC_HIGH,
    LASER_CONTROLLER_FAULT_LD_LOOP_BAD,
    LASER_CONTROLLER_FAULT_UNEXPECTED_CURRENT,
    LASER_CONTROLLER_FAULT_CURRENT_MISMATCH,
    LASER_CONTROLLER_FAULT_TEC_NOT_SETTLED,
    LASER_CONTROLLER_FAULT_TEC_IMPLAUSIBLE,
    LASER_CONTROLLER_FAULT_ILLEGAL_BUTTON_STATE,
    LASER_CONTROLLER_FAULT_UNEXPECTED_STATE,
    LASER_CONTROLLER_FAULT_COMMS_TIMEOUT,
    LASER_CONTROLLER_FAULT_SERVICE_OVERRIDE_REJECTED,
} laser_controller_fault_code_t;

typedef struct {
    bool active;
    uint32_t counter;
    laser_controller_time_ms_t last_timestamp_ms;
    laser_controller_fault_code_t code;
    laser_controller_fault_class_t fault_class;
} laser_controller_fault_record_t;

const char *laser_controller_fault_code_name(laser_controller_fault_code_t code);
const char *laser_controller_fault_class_name(laser_controller_fault_class_t fault_class);
